version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: targetadmission-api
    restart: always
    env_file:
      - .env
    ports:
      - "8080:4000"